# Generated by Django 5.2.13 on 2026-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_tasks_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
